version: 2
updates:

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "shakewell"
    assignees:
      - "shakewell"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope